### ISSUE TITLE
Translating guidelines

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#230]
There is currently a [`CONTRIBUTING.md`](https://github.com/HugoGiraudel/sass-guidelines/blob/gh-pages/CONTRIBUTING.md) file at the root of the repository, containing a lot of information about how to deal with Git, especially the existing branching system.

I just created a [`TRANSLATING.md`](https://github.com/HugoGiraudel/sass-guidelines/blob/gh-pages/TRANSLATING.md) file at the root of the repository, containing a lot of information about what should be translated, what shouldn't, and how to get started.

Then each language folder should have its own `README.md` file containing language-specific notes. I created a template for this here: https://github.com/HugoGiraudel/sass-guidelines/blob/gh-pages/en/README.md. 

Our kind Portuguese-speaking friends already started this on their side: https://github.com/HugoGiraudel/sass-guidelines/tree/gh-pages/pt#notas-de-tradução. Thank you. :)

**Comment by magalhini** [comment]
This makes everything so much more straightforward, I love it.

The guidelines for each language are of incredible importance, it would have saved us (PT translators) a lot of hassle when reviewing multiple translations from different people, since everyone adopted different (but all valid) styles of translation.

My only suggestion would be to deeply recommend translators to begin defining the `README` of their own language, in order to avoid future collisions between styles.
