### ISSUE TITLE
Highlight current section in sidebar on large screens

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-guidelines#241]
Ping @morkro.

**Comment by morkro** [comment]
Alright I got it.
I had to refactor the code a bit, but added comments to every function to make it understandable whats going on. I made the whole application logic a bit more modular, hope that's fine for you.

I also removed `debounce()`, as the performance doesn't seem to be affected at all _(see [#242](https://github.com/HugoGiraudel/sass-guidelines/issues/242))_. If it does affect the performance on weaker machines, it shouldn't be a problem to add it again. Some feedback here would be great.

I also added an `evalClientResolution()` function which uses [`matchMedia`](https://developer.mozilla.org/de/docs/Web/API/Window/matchMedia), so that the effect only appears on resolutions where the table of contents is in the sidebar.


**:computer: Tested devices:**
- MacBook Pro
- Acer Ultrabook (Windows)
- HTC One M7

**:tv: Tested browsers:**
- Latest Chrome (44) && Chrome Mobile
- Latest Firefox (39)
- Safari 8
- Opera 30
- IE 9+

If I forgot or broke something, please tell me :angel:
