### ISSUE TITLE
How about moving explanatory files to the wiki?

### ISSUE THREAD

**Issue by morkro** [HugoGiraudel/sass-guidelines#243]
This is something I've always been puzzled about on GitHub. 
Why don't we move all explanatory Markdown files (such as [`TRANSLATING.md`](https://github.com/HugoGiraudel/sass-guidelines/blob/gh-pages/TRANSLATING.md) or [`CONTRIBUTING.md`](https://github.com/HugoGiraudel/sass-guidelines/blob/gh-pages/CONTRIBUTING.md)) to the supported wiki pages? Why don't we use the wiki at all?

I think these files shouldn't really belong to the projects directory, but rather as an addition to the repository.

For instance the `CONTRIBUTING.md` mostly explains how to work with Git and this project in general. If you would move Sass-Guidelines from GitHub (or even Git) away to another version control system, the file would loose it's context.

Maybe I'm really overthinking this, but what do you think?

**Comment by HoBi** [comment]
Well, that may be true, but on the other hand:

if you clone the repository for a purpose of translating guidelines to some language, you should be able to read important files such as TRANSLATING.md or CONTRIBUTING.md, don't you?

Or can I take look to the wiki inside of git (w/o opening a browser), somehow?

**Comment by HugoGiraudel** [comment]
Because I dislike GitHub wikis, and I know for a fact that I'm not the only one. Usability is really not great, finding access is terrible, and basically everything is just fine in either one or two correctly named Markdown files in the repository if there is not much content, or a dedicated site if there is a lot.

If you have a good reason to enforce the use of GitHub wikis @morkro, please tell but until then that's a no go for me. I hope you don't mind.

PS: I am not going to move this project on SVN or Mercurial anytime soon by the way. Not gonna happen. ;)
