### ISSUE TITLE
Rename `utils` folder

### ISSUE THREAD

**Issue by macmladen** [HugoGiraudel/sass-guidelines#266]
I'd propose a change from `utils` to `abstracts` in order to better reflect its nature that it does not generate any code (or output) as all things that it contains are just **abstracts** (being variables, functions and mixins).

**Comment by HugoGiraudel** [comment]
In favor: https://twitter.com/Maxwell_Dev/status/653556718941638656.

**Comment by davidkpiano** [comment]
My two cents:

My first thought wouldn't be to use `utils` either, because it implies something supplementary rather than necessary, which variables, functions, and mixins (more often than not) end up being.

However, I think `abstracts` further _abstracts_ (pun intended) the meaning of the things inside of `utils`, by describing how they are presented, rather than what they are actually for. I wouldn't intuitively know what an `abstract` is for.

Personally, I think there should be a separation of **configuration** (or settings) and utility functions/mixins. In my stylesheets that follow the 7-1 architecture, I actually put variables in `base` files because semantically, that's where I feel they belong (such as variables for typography, grid, colors, etc.)

If anything, don't change the name and just add a note saying that the folder name isn't set in stone, and can be adjusted based on personal preferences. I think `utils` or `utilities` is just fine for describing utility functions and mixins. It's semantic.

**Comment by morkro** [comment]
`helper/`?

**Comment by tzi** [comment]
I also think "utils" is not the best name.

"utils" refer more to me to atomic classes. 

I vote for or "configurations" or "settings".
"abstracts" is not my favorite, but it is correct ;)

Cheers,
Thomas.

**Comment by long-lazuli** [comment]
I'm also not fan of `utils`, I hesitate between `abstracts` and `helpers`.
On my projects, I use `commons/placeholders` and `commons/mixins`.

**Comment by HugoGiraudel** [comment]
Will be renamed in 1.3, probably *abstracts*.

**Comment by HugoGiraudel** [comment]
Done as part of 1.3 with https://github.com/HugoGiraudel/sass-guidelines/commit/ebeed1197fcce04aec07609b829c19e5dcc9d426.
